name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        target:
          - aarch64-linux-musl
          - x86_64-linux-musl

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure caching 
        uses: actions/cache@v3
        with:
          key: ${{ matrix.os }}-${{ matrix.target }}-${{ hashFiles('**/Makefile') }}
          path: |
            Sources/
            output/
            binutils-*/
            gcc-*/
            musl-*/
            gmp-*/
            mpc-*/
            mpfr-*/
            build-*/
            linux-*/
            isl-*/
            build/
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.target }}-
            ${{ matrix.os }}-

      - name: Build MUSL
        run: TARGET=${{ matrix.target }} make -j2 --no-print-directory >/dev/null || make

      - name: Package outputs
        run: tar -cf musl-${{ matrix.os }}-${{ matrix.target }}.tgz -C build/local ${{matrix.target}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: musl-${{ matrix.os }}-${{ matrix.target }}.tgz
          path: musl-${{ matrix.os }}-${{ matrix.target }}.tgz
